services:
  postgres:
    image: postgres:17
    container_name: ludoteca-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ludoteca
      POSTGRES_USER: ludoteca_user
      POSTGRES_PASSWORD: ludoteca_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
